apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/namespace.yaml
- base/argocd-server-http-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patches:
- path: overlays/production/argocd-server-service.yaml
- path: overlays/production/argocd-cmd-params-cm.yaml